name: mantra
on: 
    push:
        branches: [ main ]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    # Updates wiki-links in the wiki.
    #
    # [req:wiki.link.update](5-REQ-wiki.link.update#wikilinkupdate-automatically-update-wiki-links)
    mantra-link:
        runs-on: ubuntu-latest
        container:
            image: manuelhatzl/mantra:latest

        steps:
            - uses: actions/checkout@v3
              with:
                path: './req_folder'
                sparse-checkout: 5-Requirements

            - uses: actions/checkout@v3
              with:
                path: './wiki_folder'
                # PAT with 'workflow' permission required in case wiki-links in workflow files get updated
                token: ${{ secrets.MANTRA_WIKI_TOKEN }}

            - name: update-links
              run: mantra link --wiki-url-prefix="" ./req_folder ./wiki_folder

            - name: push-changes
              working-directory: ./wiki_folder
              # In case nothing changed
              continue-on-error: true
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git status
                git add .
                git commit -m "chore: update wiki-links in wiki repository"
                git push
